modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "myosotis"
version = "${version}"
displayName = "Myosotis"
authors = "cao_awa, 草二号机"
description = "Myosotis is minecraft mod for the latest minecraft version that makes your death be more funny and less frustrating."
#logoFile = ""

[[dependencies.myosotis]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.myosotis]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.9]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "myosotis.mixins.json"
